- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer_msgs/CHANGELOG.rst
- shorten uuid to show
- use smaller font size
> Chore/perception UUID

- driving_log_replayer/launch/localization.launch.py
> chore: remap tf in bag

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> Chore/release 1.0.1

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> Chore/release 1.0.2

- ReleaseNotes.md
> chore: fix lint

- driving_log_replayer/launch/perception.launch.py
closes: #11
- delete use pointcloud container false
> feat: delete use pointcloud container false

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> release: 1.0.3

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: change log

- driving_log_replayer/driving_log_replayer/node_common.py
> fix: cast number from yaml file

- driving_log_replayer/scripts/perception_evaluator_node.py
> fix: frame pass fail logic

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.0.8

- requirements.txt
> fix: dependency

- docs/use_case/obstacle_segmentation.en.md
- docs/use_case/obstacle_segmentation.ja.md
- docs/use_case/performance_diag.en.md
- docs/use_case/performance_diag.ja.md
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/src/obstacle_segmentation_evaluator_component.cpp
- sample/obstacle_segmentation/scenario.yaml
- sample/obstacle_segmentation/scenario_detection_only.yaml
- sample/obstacle_segmentation/scenario_non_detection_only.yaml
- support 3 test mode for obstacle_segmentation
シナリオConditionsのキーObstacleDetectionをDetectionに変更して、UseCaseFormatVersionを0.2.0に更新しました。
1. シナリオのObstacleDetectionをDetectionに置換して実行してDetectionとNonDetection両方実行されることを確認する 
2. NonDetection: nullにして実行してDetectionだけ実行されることを確認する
3. Detection: nullにしてNonDetectionだけ実行されることを確認する
Change the key ObstacleDetection in ScenarioConditions to Detection and update the UseCaseFormatVersion to 0.2.0.
1. Replace ObstacleDetection in the scenario with Detection and run to confirm that both Detection and NonDetection are executed.
2. NonDetection: set to null and run to confirm that only Detection is executed
3. Detection: Set to null to confirm that only NonDetection is executed.
> feat: #33 test mode for obstacle segmentation

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.0.11

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.0.12

- driving_log_replayer/src/obstacle_segmentation_evaluator_component.cpp
Changes have been made to the status name in Autoware's diagnostics.
Autoware Foundation autoware.universe
https://github.com/autowarefoundation/autoware.universe/pull/2120
TIER IV autoware.universe
https://github.com/tier4/autoware.universe/pull/159
update autoware workspace and apply this PR
> feat(obstacle_segmentation): #39 update diagnostic status name

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.1.0

- driving_log_replayer_analyzer/README.md
- driving_log_replayer_analyzer/config/config.yaml
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/calc.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/config.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/common.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/non_detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/position.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/summary.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/jsonl_parser.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/main.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/bird_view_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/line_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/plot_base.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/scatter_plot.py
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
Add `driving_log_replayer_analyzer` to visualize `result.jsonl` file.
> add driving_log_replayer_analyzer

- driving_log_replayer_analyzer/README.md
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/calc.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/non_detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/jsonl_parser.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/main.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/bird_view_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/line_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/scatter_plot.py
- setup.cfg
> fix: pre-commit-check

- .vscode/settings.json
- dependency.repos
- docs/.pages
- docs/analyzer/images/future_work.drawio.svg
- docs/analyzer/index.en.md
- docs/analyzer/index.ja.md
- driving_log_replayer/CMakeLists.txt
- driving_log_replayer/launch/obstacle_segmentation_analyze.launch.py
- driving_log_replayer/scripts/obstacle_segmentation_analyzer.py
- driving_log_replayer_analyzer/CMakeLists.txt
- driving_log_replayer_analyzer/README.md
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/calc.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/config.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/common.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/non_detection.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/position.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/summary.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/jsonl_parser.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/main.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/bird_view_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/line_plot.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/plot_base.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/scatter_plot.py
- driving_log_replayer_analyzer/package.xml
- github_action_dependency.repos
- poetry.lock
- pyproject.toml
- add Japanese document
- add cli command
- add ros package
Check that there are no problems with the document's FUTURE WORK policy.
https://tier4.github.io/driving_log_replayer/ja/analyzer/
https://user-images.githubusercontent.com/16977736/205013187-8870fa44-da55-4a59-a4fc-2dd675e7911a.mp4
> feat: analyzer

- .driving_log_replayer.cspell.json
- .github/workflows/spell-check.yaml
> feat: add local cspell dictionary

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.2

- .github/workflows/colcon-test.yaml
- docs/use_case/obstacle_segmentation.en.md
- docs/use_case/obstacle_segmentation.ja.md
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- sample/obstacle_segmentation/scenario.yaml
- sample/obstacle_segmentation/scenario_detection_only.yaml
- sample/obstacle_segmentation/scenario_non_detection_only.yaml
-  set evaluation period for each bbox
please use perception_eval below
https://github.com/tier4/autoware_perception_evaluation/pull/22
> feat: #51 set evaluation period for each bbox

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.3

- ReleaseNotes.md
> chore: release 1.1.4

- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> fix: #61 marker color

- ReleaseNotes.md
- pyproject.toml
> chore: release 1.1.5

- .vscode/settings.json
- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- docs/use_case/performance_diag.en.md
- docs/use_case/performance_diag.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- use ad-api to set initial pose
> feat: #64 use ad api

- ReleaseNotes.md
- pyproject.toml
> chore: release 1.1.6

- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- delete uninitialized publisher
> fix: delete uninitialized publisher

- .vscode/settings.json
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> fix: #69 use map fit

- ReleaseNotes.md
- pyproject.toml
> chore: release 1.1.7

- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- Change the color of the bounding box according to the result of the TOPIC RATE
> fix: change bounding box color

- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- fix infinite wait at initialization
> fix: fix infinite wait at initialization

- ReleaseNotes.md
- pyproject.toml
> chore: release 1.1.8

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/package.xml
> feat: #34 use mcap

- driving_log_replayer/driving_log_replayer/obstacle_segmentation_analyzer.py
> fix: no module named plotly

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.9

- .github/workflows/colcon-test.yaml
- README.md
- driving_log_replayer/driving_log_replayer/launch_common.py
- poetry.lock
- pyproject.toml
> feat: #57 use sim time option in record

- driving_log_replayer/package.xml
- driving_log_replayer_analyzer/package.xml
- driving_log_replayer_msgs/package.xml
- pyproject.toml
- Corrected description of license
> chore: license

- driving_log_replayer/scripts/performance_diag_evaluator_node.py
closes: #84
- handle TransformException
> fix: catch TransformException

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.10

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.1.11

- .pre-commit-config.yaml
- pyproject.toml
> feat: update pre-commit-shfmt

- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- sample/perception/scenario.yaml
> feat: #97 update perception eval

- .vscode/settings.json
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/obstacle_segmentation.launch.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- change  topic to get stop_reasons
> feat: #96 topic stop reasons

- .pre-commit-config.yaml
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.12

- driving_log_replayer/driving_log_replayer/obstacle_segmentation_analyzer.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/analysis/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/analysis/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/scatter_plot.py
- port features developed in private repositories
> feat: #93 update obstacle segmentation analyzer

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.13

- mkdocs.yml
- udpate for mkdocs material 9
> feat: add setting from version 9

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.14

- docs/use_case/index.ja.md
Fix link error at https://tier4.github.io/driving_log_replayer/ja/use_case/
> chore: fix link error

- .driving_log_replayer.cspell.json
- driving_log_replayer/driving_log_replayer/node_common.py
- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/package.xml
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_database_result.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_cli/simulation/result.py
- sample/perception/scenario.yaml
- replace invalid json value (NaN, Infinity) to null
> fix: #108 perception json value

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.16

- driving_log_replayer/config/autoware.rviz
- driving_log_replayer/config/localization.rviz
- driving_log_replayer/config/obstacle_segmentation.rviz
- driving_log_replayer/config/perception.rviz
> feat: update rviz

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.17

- driving_log_replayer/scripts/perception_evaluator_node.py
- update for dependent library
> feat: update for perception_eval PR #12

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.1.18

- driving_log_replayer/scripts/perception_evaluator_node.py
- Fixed issue with assignments not being processed.
> fix: count tp fp fn

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.1.19

- ReleaseNotes.md
- pyproject.toml
> chore: release 1.1.20

- ReleaseNotes.md
> chore: release 1.1.21

- driving_log_replayer/launch/performance_diag.launch.py
- drop recording unused camera topic
> chore: drop camera image

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.1.22

- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
- sample/perception/scenario.yaml
> docs: fix perception key name

- docs/use_case/perception.ja.md
- docs/use_case/perception_2d.ja.md
- docs/use_case/traffic_light.md
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- sample/perception/scenario.yaml
- sample/perception_2d/scenario.yaml
- sample/traffic_light/scenario.yaml
- 2d detection
- traffic light
I would like you to review the document.
https://github.com/tier4/driving_log_replayer/blob/feat/%23104-2d-perception/docs/use_case/perception_2d.ja.md
https://github.com/tier4/driving_log_replayer/blob/feat/%23104-2d-perception/docs/use_case/traffic_light.md
> feat: #104 2d perception

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.2.0

- driving_log_replayer/scripts/localization_evaluator_node.py
- update for https://github.com/autowarefoundation/autoware.universe/pull/2724
> feat: delete fit_map_height service call

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.0

- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
- performance_diag result.jsonl msg format
> chore: fix output msg format

- ReleaseNotes.md
> chore: release 1.3.2

- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- for performace_diag evaluation
- same as https://github.com/tier4/driving_log_replayer/pull/129
> feat: delete fit map height service call

- sample/localization/scenario.ja.yaml
- sample/localization/scenario.yaml
- sample/localization/scenario_use_gnss.yaml
- sample/performance_diag/scenario.ja.yaml
- sample/performance_diag/scenario.yaml
> docs: update initialpose comment

- .clang-format
- .clang-tidy
- .markdown-link-check.json
- .markdownlint.yaml
- .pre-commit-config.yaml
- .prettierrc.yaml
- .shellcheckrc
- .yamllint.yaml
- CPPLINT.cfg
- update linter and formatter settings
> feat: apply autoware universe linter formatter settings

- docs/use_case/perception_2d.en.md
- docs/use_case/perception_2d.ja.md
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
> feat: tracking2d evaluation

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.5

- ReleaseNotes.md
> chore: release 1.3.6

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- sample/perception/scenario.ja.yaml
- sample/perception/scenario.yaml
- sample/perception_2d/scenario.ja.yaml
- sample/perception_2d/scenario.yaml
- support ignore_attributes
- https://github.com/tier4/autoware_perception_evaluation/pull/66
> feat: #145 perception support ignore attributes

- driving_log_replayer/launch/obstacle_segmentation.launch.py
- driving_log_replayer/src/obstacle_segmentation_evaluator_component.cpp
- check if input polygon is clockwise
> feat: check if input polygon clockwise

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- handle incompatible scenario
> fix: Handling incompatible scenario

- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
> fix: #156 initialpose service call

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.7

- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
> docs: update bag topic

- ReleaseNotes.md
- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.8

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/driving_log_replayer/shutdown_once.py
- driving_log_replayer/launch/obstacle_segmentation.launch.py
- apply [ShutdownOnce](https://github.com/tier4/scenario_simulator_v2/blob/master/test_runner/scenario_test_runner/scenario_test_runner/shutdown_once.py)
> feat: apply ShutdownOnce

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.9

- docs/use_case/index.ja.md
> docs: index.ja.md

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
- release (to deploy document)
> chore: release 1.3.10

- driving_log_replayer_cli/simulation/generate.py
- support scenario.yml
Change the name of the scenario in the data folder of driving_log_replayer from scenario.yaml to scenario.yml and run the simulation run command
> feat: support scenario.yml

- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
> fix: catch transform exception

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.11

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.12

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.13

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/localization.launch.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- sample/localization/scenario.ja.yaml
- sample/localization/scenario.yaml
- use map_height_fitter to correct z value
Please use autoware.universe in the following PR branch
https://github.com/autowarefoundation/autoware.universe/pull/4128
Then, please confirm below
- The z-coordinate of the sample scenario is set to 0.0.
- The localization.launch file calls the launch of map_height_fitter.
- The z-coordinate is corrected, causing the initial position to match.
> feat: #175 map height fitter

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/localization.launch.py
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
> feat: map height fitter for diag

- ReleaseNotes.md
- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.3.14

- .github/workflows/spell-check.yaml
- pyproject.toml
> feat: ci use tier4 cspell-dicts

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.15

- driving_log_replayer/CMakeLists.txt
https://github.com/autowarefoundation/autoware_common/pull/186/files
- apply https://github.com/autowarefoundation/autoware_common/pull/186/files
> fix: colcon build error

- .github/workflows/spell-check.yaml
- ReleaseNotes.md
- docs/overview/index.en.md
- docs/overview/index.ja.md
- docs/quick_start/localization.en.md
- docs/quick_start/localization.ja.md
- docs/use_case/index.ja.md
- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/CMakeLists.txt
- driving_log_replayer/config/localization_topics.yaml
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/package.xml
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_analyzer/package.xml
- driving_log_replayer_cli/simulation/generate.py
- driving_log_replayer_msgs/CHANGELOG.rst
- driving_log_replayer_msgs/package.xml
- pyproject.toml
- sample/localization/scenario.ja.yaml
- sample/localization/scenario.yaml
> feat: galactic merge develop

- docs/quick_start/localization.en.md
- docs/quick_start/localization.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- add likelihood average and stddev to summary message
Run the following tutorial using awf/autoware
https://tier4.github.io/driving_log_replayer/quick_start/localization/
Confirm that the mean and standard deviation of the likelihood are output in the summary message after execution as follows
```shell
test case 1 / 1 : use case: sample
--------------------------------------------------
TestResult: Passed
Passed: Convergence (Passed): 281 / 281 -> 100.00%, Reliability (Passed): NVTL Sequential NG Count: 0 (Total Test: 283, Average: 2.476907772225963, StdDev: 0.042055602266257264), NDT Availability (Passed): NDT available
```
> feat: localization likelihood average std_dev

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.16

- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- driving_log_replayer/scripts/localization_evaluator_node.py
- delete converged condition to start evaluation
1. please use tutorial [dataset](https://tier4.github.io/driving_log_replayer/quick_start/localization/)
2. change z value of scenario 20.0 -> 0.0
- https://github.com/tier4/driving_log_replayer/blob/develop/sample/localization/scenario.yaml#L25
3. run simulation
4.  confirm result like blow
```shell
test case 1 / 1 : use case: sample
--------------------------------------------------
TestResult: Passed
Passed: Convergence (Passed): NotTested, Reliability (Passed): NotTested, NDT Availability (Passed): NDT available
test case 1 / 1 : use case: sample
--------------------------------------------------
TestResult: Failed
Failed: Convergence (Passed): NotTested, Reliability (Failed): NVTL Sequential NG Count: 10 (Total Test: 290, Average: …
```
> feat: #192 delete converged condition to start evaluation

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.3.17

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/localization.launch.py
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
- sample/localization/scenario.ja.yaml
- sample/localization/scenario.yaml
- release 1.4.0
- map_height_fitter
afeter https://github.com/tier4/driving_log_replayer/pull/191
> chore: release 1.4.0

- ReleaseNotes.md
- docs/quick_start/localization.en.md
- docs/quick_start/localization.ja.md
- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/config/localization_topics.yaml
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/package.xml
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_analyzer/package.xml
- driving_log_replayer_msgs/CHANGELOG.rst
- driving_log_replayer_msgs/package.xml
- pyproject.toml
> chore: merge main

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/package.xml
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
- release
- release yabloc evaluation
> chore: release 1.4.1

- driving_log_replayer/scripts/perception_evaluator_node.py
- sample/perception/scenario.fp.ja.yaml
> feat: #199 perception fp validation

- docs/quick_start/eagleye.en.md
- docs/quick_start/eagleye.ja.md
- docs/scenario_format/index.en.md
- docs/scenario_format/index.ja.md
- docs/use_case/.pages
- docs/use_case/eagleye.en.md
- docs/use_case/eagleye.ja.md
- driving_log_replayer/CMakeLists.txt
- driving_log_replayer/launch/eagleye.launch.py
- driving_log_replayer/launch/yabloc.launch.py
- driving_log_replayer/scripts/eagleye_evaluator_node.py
- sample/.driving_log_replayer.config.toml
- sample/eagleye/scenario.yaml
I'd like to add Eagleye evaluator scenario.
INTERNAL LINKS:
https://star4.slack.com/archives/C02G6HT8TNX/p1688007226092479
https://star4.slack.com/archives/C02G6HT8TNX/p1689208258348619
Please use this rosbag as an input_bag: [TIER IV INTERNAL LINK](https://drive.google.com/file/d/1womy7nih7biR6i2DfRmYfBnyCGqw642G/view?usp=drive_link)
The steps are mostly same as YabLoc. You don't need to filter the rosbag by timestamp, though.
The output should look like this:
```
<< show test result >>                                                                                                                                                                                             
test case 1 / 1 : use case: sample …
```
> feat: add eagleye evaluation

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- sample/perception/scenario.fp.ja.yaml
- sample/perception/scenario.fp.yaml
- sample/perception/scenario.ja.yaml
- sample/perception/scenario.yaml
- sample/traffic_light/scenario.ja.yaml
- sample/traffic_light/scenario.yaml
- update sample scenario
- handle key not found
> feat: update sample scenario and set None if dict key is not found

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.5.0

- driving_log_replayer/scripts/perception_evaluator_node.py
- Changed to write the results of fp evaluation to result.jsonl
Changed to save what is written out in the console log to result.jsonl as follows
```shell
[perception_evaluator_node.py-65] [2023-08-09 14:16:16,654] [INFO] [perception_evaluator_node.py:459 get_fp_result] uuid: 2b3dbc70e876f6829fb27301e27316f0, TP: inf, FP: 1.000, TN: inf, FN: inf
[perception_evaluator_node.py-65] Total: [0, 1, 3], TP: [], FP: [0, 1, 3], TN: [], FN: []
[perception_evaluator_node.py-65] [2023-08-09 14:16:16,655] [INFO] [perception_evaluator_node.py:459 get_fp_result] uuid: cb1040491bbcf642078c00a7a75c95f9, TP: inf, FP: 1.000, TN: inf, FN: inf
[perception_evaluator_node.py-65] Total: [0, 1, 3, 4, 5, 7, 8, 10, 11, 13, 15, 17, 18, 19], TP: [], FP: [0, 1, 3, 4, 5, 7, 8, 10, 11, 13, 15, 17, 18, 19], TN: [], FN: …
```
> fix: store fp result in result.jsonl

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.5.1

- driving_log_replayer/scripts/debug/perception_load_scene_result.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- driving_log_replayer_cli/core/config.py
- pyproject.toml
> refactor: apply errmsg em rules

- driving_log_replayer_analyzer/driving_log_replayer_analyzer/__main__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/analysis/__init__.py
- driving_log_replayer_cli/__init__.py
- driving_log_replayer_cli/configuration/__init__.py
- driving_log_replayer_cli/simulation/__init__.py
- pyproject.toml
> refactor: apply pie rules

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/driving_log_replayer/shutdown_once.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- driving_log_replayer_cli/simulation/generate.py
- pyproject.toml
> refactor: apply return ret rules

- driving_log_replayer/scripts/eagleye_evaluator_node.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer/scripts/yabloc_evaluator_node.py
- pyproject.toml
> refactor: apply type checking TCH rules

- driving_log_replayer/driving_log_replayer/node_common.py
- driving_log_replayer/driving_log_replayer/shutdown_once.py
- driving_log_replayer/scripts/debug/obstacle_segmentation_load_scene_result.py
- driving_log_replayer/scripts/debug/perception_load_scene_result.py
- driving_log_replayer/scripts/eagleye_evaluator_node.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer/scripts/yabloc_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_cli/simulation/result.py
- pyproject.toml
> refactor: apply pyupgrade

- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/__init__.py
- driving_log_replayer_cli/simulation/generate.py
- driving_log_replayer_cli/simulation/result.py
- pyproject.toml
> refactor: apply simplify SIM rules

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/eagleye.launch.py
- driving_log_replayer/launch/localization.launch.py
- driving_log_replayer/launch/obstacle_segmentation.launch.py
- driving_log_replayer/launch/perception.launch.py
- driving_log_replayer/launch/perception_2d.launch.py
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/launch/traffic_light.launch.py
- driving_log_replayer/launch/yabloc.launch.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/analysis/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/__init__.py
- pyproject.toml
> refactor: apply ruff specific RUF rules

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- pyproject.toml
> fix: handle 2d evaluation task error

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.5.2

- poetry.lock
- pyproject.toml
> chore: update pyproject.toml

- docs/quick_start/.pages
- docs/quick_start/eagleye.en.md
- docs/quick_start/eagleye.ja.md
- sample/eagleye/scenario.yaml
Add quick start guide for Eagleye
Please follow the docs and verify that it works.
None
> chore(docs): add eagleye quick start

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/package.xml
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_analyzer/package.xml
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.5.3

- mkdocs.yml
refer https://ultrabug.github.io/mkdocs-static-i18n/setup/upgrading-to-1/
- update mkdocs i18n setting
> chore: update mkdocs.yml

- docs/quick_start/eagleye.en.md
Update Eagleye sample rosbag link to the public one
Click the link and verify that you can access it via secret mode
> chore(docs): update eagleye sample rosbag link

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.5.4

- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
> refactor: obstacle segmentation abc

- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/scripts/debug/perception_load_scene_result.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/bird_view_plot.py
- driving_log_replayer_cli/simulation/result.py
- pyproject.toml
> refactor: apply ruff rules

- .github/workflows/colcon-test.yaml
- driving_log_replayer/CMakeLists.txt
- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/driving_log_replayer/obstacle_segmentation_analyzer.py
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/include/driving_log_replayer/obstacle_segmentation_evaluator_component.hpp
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/analysis/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/plot/__init__.py
- driving_log_replayer_cli/core/config.py
- driving_log_replayer_cli/simulation/generate.py
- poetry.lock
- pyproject.toml
> feat!: drop galactic support

- .vscode/c_cpp_properties.json
- README.md
- ReleaseNotes.md
- docs/quick_start/installation.en.md
- docs/quick_start/installation.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore!: release 1.6.0

- driving_log_replayer/driving_log_replayer/launch_common.py
- restore launch argument default value
> fix: restore default value

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.6.1

- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/driving_log_replayer/result.py
> feat: topic result

- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/driving_log_replayer/result.py
- change initial value of topic result
> chore: change topic result success initial value

- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/test/unittest/test_localization.py
- update localization availability
> feat: update localization availability

- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/test/unittest/test_localization.py
> chore: evaluation item

- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/test/unittest/test_localization.py
> feat: add frame success

- driving_log_replayer/test/unittest/test_localization.py
> chore: update variable name

- driving_log_replayer/driving_log_replayer/eagleye.py
- driving_log_replayer/scripts/eagleye_evaluator_node.py
- driving_log_replayer/test/unittest/test_eagleye.py
- add eagleye test
same as yabloc [PR](https://github.com/tier4/driving_log_replayer/pull/252)
> feat: eagleye test

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.6.2

- docs/quick_start/yabloc.en.md
- docs/quick_start/yabloc.ja.md
Fix URL of Yabloc quickstart
Confirmed that the 
Download the URL link and confirm that the file name aligns with the docs
None
> fix(yabloc): fix rosbag url

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.6.3

- .github/workflows/deploy-document.yaml
> fix: add mkdocs library

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.6.4

- driving_log_replayer/CMakeLists.txt
- requirements.txt
Add operation for force installing python libraries to ensure ROS execution while building
> build: add requirements and install operation to overwrite python libraries

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.6.5

- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/test/unittest/test_perception_eval_conversions.py
- add perception_eval_conversions unit test
> feat: eval_conversions add test

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.6.6

- driving_log_replayer/driving_log_replayer/criteria/perception.py
- fix [lint error](https://github.com/tier4/driving_log_replayer/actions/runs/6482494443/job/17602126442)
- refer https://docs.astral.sh/ruff/rules/typing-only-third-party-import/
> fix: TCH002

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.7.0

- driving_log_replayer_cli/simulation/generate.py
- driving_log_replayer_cli/simulation/run.py
> refactor: cli generate command

- .vscode/launch.json
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/driving_log_replayer/obstacle_segmentation_analyzer.py
- driving_log_replayer/scripts/debug/obstacle_segmentation_load_scene_result.py
- driving_log_replayer/scripts/debug/perception_load_scene_result.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_database_result.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/config/obstacle_segmentation.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/obstacle_segmentation.py
- driving_log_replayer_cli/core/config.py
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/result.py
- pyproject.toml
> refactor: use pathlib

- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_database_result.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_cli/simulation/__init__.py
> chore: delete meaningless joinpath

- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/driving_log_replayer/result.py
> refactor: common module

- docs/use_case/traffic_light.en.md
- docs/use_case/traffic_light.ja.md
- update ml model download
- update ml model to use
> docs: update perception ml model

- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
- docs/use_case/perception_2d.en.md
- docs/use_case/perception_2d.ja.md
> docs: update ml model

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.8.1

- driving_log_replayer_cli/simulation/generate.py
> fix: add parents option

- driving_log_replayer/driving_log_replayer/ar_tag_based_localizer.py
- driving_log_replayer/driving_log_replayer/eagleye.py
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/driving_log_replayer/perception.py
- driving_log_replayer/driving_log_replayer/perception_2d.py
- driving_log_replayer/driving_log_replayer/performance_diag.py
- driving_log_replayer/driving_log_replayer/result.py
- driving_log_replayer/driving_log_replayer/traffic_light.py
- driving_log_replayer/driving_log_replayer/yabloc.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/test/unittest/test_perception_2d.py
> feat: perception 2d test

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.8.2

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.8.3

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.8.4

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.9.0

- driving_log_replayer/driving_log_replayer/perception_2d.py
- driving_log_replayer/driving_log_replayer/performance_diag.py
- driving_log_replayer/test/unittest/test_performance_diag.py
> refactor: diag

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_perception_2d.py
- driving_log_replayer/test/unittest/test_traffic_light.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.9.1

- README.md
> docs: update release process

- driving_log_replayer/driving_log_replayer/evaluator.py
> chore: type hint

- driving_log_replayer_cli/simulation/generate.py
- driving_log_replayer_cli/simulation/run.py
- pyproject.toml
> fix: shell true for security

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.10.1

- driving_log_replayer/driving_log_replayer/scenario.py
- driving_log_replayer/test/unittest/test_perception.py
- sample/perception/scenario.criteria.custom.yaml
- sample/perception/scenario.fp.ja.yaml
- sample/perception/scenario.fp.yaml
- sample/perception/scenario.ja.yaml
> chore: test perception criteria custom level

- .github/workflows/colcon-test.yaml
- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/generate.py
- pyproject.toml
- If `perception_mode`  is not given as argument, use default `perception_mode` written in `autoware.launch`
> fix: perception mode default

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
> chore: release 1.10.2

- .github/workflows/colcon-test.yaml
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.10.3

- .github/workflows/pre-commit.yaml
> chore: use pre-commit/action

- .github/workflows/pre-commit.yaml
> fix: fetch-depth

- driving_log_replayer/driving_log_replayer/launch_common.py
- driving_log_replayer/launch/ar_tag_based_localizer.launch.py
- driving_log_replayer/launch/eagleye.launch.py
- driving_log_replayer/launch/localization.launch.py
- driving_log_replayer/launch/obstacle_segmentation.launch.py
- driving_log_replayer/launch/perception.launch.py
- driving_log_replayer/launch/perception_2d.launch.py
- driving_log_replayer/launch/performance_diag.launch.py
- driving_log_replayer/launch/traffic_light.launch.py
- driving_log_replayer/launch/yabloc.launch.py
> refactor: launch arg

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.10.5

- .vscode/settings.json
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/test/unittest/test_perception_eval_conversions.py
- check number of footprint
- if footprint is invalid, shutdown node 
closes #331
> fix: #331 check footprint length

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.10.6

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.11.0

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.11.1

- driving_log_replayer_cli/core/config.py
- driving_log_replayer_cli/core/scenario.py
- add mode for pydantic validator
> chore: add mode

- docs/overview/images/overview.drawio.svg
- docs/overview/setup.en.md
- docs/overview/setup.ja.md
- docs/quick_start/ar_tag_based_localizer.en.md
> docs: fix command

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/package.xml
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
- release 1.12.0
- breaking change for `perception`
Do not merge until miursh's APPROVE.
> chore!: release 1.12.0

- .driving_log_replayer.cspell.json
- .vscode/settings.json
- driving_log_replayer/config/obstacle_segmentation.qos.yaml
- driving_log_replayer/launch/obstacle_segmentation.launch.py
- record `/diagnostics` for debug
> chore: record diagnostics

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.12.1

- driving_log_replayer/scripts/perception_evaluator_node.py
Related with perception eval changes in https://github.com/tier4/autoware_perception_evaluation/pull/120, 
tracking evaluation wants to interpolate ground truth objects to get more suitable comparison with estimation results.
Run tracking scenario with latest perception_eval.
> feat: enable to interpolate gt when scenario is tracking

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.12.2

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: 1.12.3

- driving_log_replayer/launch/traffic_light.launch.py
Change recorded topics in traffic_light
```
$ ros2 topic list | grep "^/clock$\|^/tf$\|^/sensing/camera/camera[67]/image_raw/compressed$\|^/perception/.*/traffic_signals$\|^/driving_log_replayer/.*"
/clock
/perception/traffic_light_recognition/camera6/classification/classified/car/traffic_signals
/perception/traffic_light_recognition/camera6/classification/classified/pedestrian/traffic_signals
/perception/traffic_light_recognition/camera6/classification/traffic_signals
/perception/traffic_light_recognition/external/traffic_signals
/perception/traffic_light_recognition/fusion/traffic_signals
/perception/traffic_light_recognition/internal/traffic_signals
/perception/traffic_light_recognition/traffic_signals
/sensing/camera/camera6/image_raw/compressed
/tf
```
Please check that the regex is …
> feat(traffic_light): change recorded topics

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.12.4

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.12.5

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: 1.13.1

- driving_log_replayer/scripts/debug/calc_transform_node.py
- driving_log_replayer/test/unittest/test_obstacle_segmentation.py
- add unit test for obstacle segmentation
> chore: add unit test

- driving_log_replayer/launch/performance_diag.launch.py
- Do not record  `concatenated/pointcloud`
> feat: drop concatenated/pointcloud

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.13.2

- driving_log_replayer/driving_log_replayer/obstacle_segmentation.py
- driving_log_replayer/test/unittest/test_obstacle_segmentation.py
> chore: unit test

- docs/use_case/obstacle_segmentation.en.md
- docs/use_case/obstacle_segmentation.ja.md
> docs: update obstacle_segmentation

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.13.3

- driving_log_replayer/package.xml
> chore: Delete confusing comments

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.13.4

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.0

- driving_log_replayer/driving_log_replayer/annotationless_perception.py
Failedしたときの結果出力を詳細にしました。Failedしたメトリクスの値と閾値を表示するようにしました。
Failed results are displayed in more detail, including the value of the failed metric and the threshold value.
before
```
TestResult: Failed
Failed: CAR (Fail, predicted_path_deviation_5.00, predicted_path_deviation_3.00) BUS (Fail, predicted_path_deviation_1.00) PEDESTRIAN (Success) BICYCLE (Success) TRUCK (Success)
```
after
```
TestResult: Failed
Failed:
CAR (Success)
BUS (Success)
PEDESTRIAN (Fail):
yaw_rate_mean: value=1.8357506956521739, threshold=(0.45335158196721326-1.813406327868853)
lateral_deviation_max: value=7.15402, threshold=(0.0-4.338506)
lateral_deviation_mean: value=0.13830618181818183, threshold=(0.034175926229508186-0.13670370491803274)
BICYCLE (Success)
TRUCK (Success)
```
> feat(annotationless_perception): output details of fail items

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.2

- driving_log_replayer_cli/core/result.py
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/run.py
> refactor: cli change structure

- driving_log_replayer_cli/__init__.py
> fix: package name

- driving_log_replayer_cli/simulation/run.py
> refactor: check UseCaseName to create command

- docs/quick_start/annotationless_perception.en.md
- docs/quick_start/annotationless_perception.ja.md
- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
- driving_log_replayer_cli/core/result.py
- driving_log_replayer_cli/core/scenario.py
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/run.py
- driving_log_replayer_cli/simulation/scenario.py
- driving_log_replayer_cli/simulation/update.py
- add command to update annotationless scenario condition
- add function to automatically update scenario after simulation run
```shell
git clone https://github.com/tier4/driving_log_replayer.git -b feat/#381-cli-update-scenario-condition
cd driving_log_replayer
pipx install . -f
dlr simulation update-condition -s ${scenario_path} -r ${result.jsonl_path} -u {existing|all}
dlr simulation run -p annotationless_perception -u {existing|all}
```
> feat: #381 cli update scenario condition

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.3

- driving_log_replayer/driving_log_replayer/evaluator.py
> revert: #319 bag controller

- driving_log_replayer/scripts/perception_evaluator_node.py
- set Result False when run time error occurs
> feat: set Result False when run time error occurs

- docs/overview/command.en.md
- docs/overview/command.ja.md
- docs/quick_start/annotationless_perception.en.md
- docs/quick_start/annotationless_perception.ja.md
- docs/quick_start/ar_tag_based_localizer.en.md
- docs/quick_start/ar_tag_based_localizer.ja.md
- docs/quick_start/eagleye.en.md
- docs/quick_start/eagleye.ja.md
- docs/quick_start/localization.en.md
- docs/quick_start/localization.ja.md
- docs/quick_start/obstacle_segmentation.en.md
- docs/quick_start/obstacle_segmentation.ja.md
- docs/quick_start/perception.en.md
- docs/quick_start/perception.ja.md
- docs/quick_start/yabloc.en.md
- docs/quick_start/yabloc.ja.md
- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/run.py
- driving_log_replayer_cli/test/simulation/test_run.py
- Changed to specify launch arguments one by one with the -l option.
```shell
-l 'arg1:=value1,arg2:=value2...'
-l arg1:=value1 -l arg2:=value2 ....
```
closes: #391
> feat: #391 update cli run option

- driving_log_replayer/driving_log_replayer/annotationless_perception.py
just change failure detail messages
```
TestResult: Failed
Failed:
BICYCLE (Fail):
yaw_rate_max: actual_value=32.605589, expected_value=(0.0-10.0)
PEDESTRIAN (Success)
CAR (Success)
BUS (Success)
TRUCK (Success)
```
> feat: change failure details message

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.4

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.5

- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
- driving_log_replayer/driving_log_replayer/perception.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- skip frame when 1 <= len(footprint.points) < 3
If the points of footprint are 1 or 2, the evaluation is skipped and the following log is written
```json
{
"Result": {
"Success": true,
"Summary": "Passed:  criteria0 (Success): 272 / 272 -> 100.00%, Passed:  criteria1 (Success): 272 / 272 -> 100.00%, Passed:  criteria2 (Success): 272 / 272 -> 100.00%"
},
"Stamp": {
"System": 1712131844.5334826,
"ROS": 1706597564.2110178
},
"Frame": {
"Warning": "Unexpected footprint length: len(perception_object.shape.footprint.points)=2",
"FrameSkip": 1
}
}
```
closes: #396
> feat: #396 drop topic footprint 1or2

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.6

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.7

- driving_log_replayer/test/unittest/test_annotationless_perception.py
> fix: annotationless_perception unit test

- pyproject.toml
- requirements-dev.lock
- requirements.lock
> chore: update pyproject.tom

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.8

- requirements.txt
- Temporary fix for colon test failure with newer version of pytest
> fix: colcon test error

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.9

- driving_log_replayer/driving_log_replayer/perception.py
- driving_log_replayer/driving_log_replayer/perception_2d.py
- driving_log_replayer/driving_log_replayer/traffic_light.py
- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_perception_2d.py
- driving_log_replayer/test/unittest/test_traffic_light.py
- set EvaluationItem.success True
> fix: set success True

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.14.10

- driving_log_replayer/driving_log_replayer/performance_diag.py
- driving_log_replayer/test/unittest/test_performance_diag.py
- change default success value
TIER IV internal
```shell
webauto ci scenario run --project-id x2_dev --scenario-id 14d57dda-4584-4adb-9bc2-b92e66eeba30 --scenario-version-id 6
```
closes: #414
> fix: default success is False

- driving_log_replayer/driving_log_replayer/obstacle_segmentation.py
- fix default value of EvaluationItem.success
same as 06fab5312529ec06573ff7aa41eea2b88119369b
> fix: obstacle segmentation default success value is False

- README.md
> docs: Why use pipx

- .vscode/launch.json
> chore: update debug setting

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.15.1

- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
> docs: update annotationless perception launch argument

- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer/test/unittest/test_lanelet2.py
- Set the distance of the nearest traffic_light from the traffic_light group
> fix: calc traffic light distance

- driving_log_replayer/driving_log_replayer/ar_tag_based_localizer.py
- driving_log_replayer/driving_log_replayer/eagleye.py
- driving_log_replayer/driving_log_replayer/localization.py
- driving_log_replayer/driving_log_replayer/yabloc.py
- driving_log_replayer/scripts/ar_tag_based_localizer_evaluator_node.py
- driving_log_replayer/scripts/eagleye_evaluator_node.py
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/yabloc_evaluator_node.py
- driving_log_replayer/test/unittest/test_ar_tag_based_localizer.py
- driving_log_replayer/test/unittest/test_eagleye.py
- driving_log_replayer/test/unittest/test_localization.py
- driving_log_replayer/test/unittest/test_yabloc.py
same as https://github.com/tier4/driving_log_replayer/pull/433
> fix: filter diagnostics

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/package.xml
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_analyzer/package.xml
- driving_log_replayer_msgs/CHANGELOG.rst
- driving_log_replayer_msgs/package.xml
- pyproject.toml
> chore: release 1.15.2

- driving_log_replayer/driving_log_replayer/perception.py
- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
- driving_log_replayer/test/unittest/test_perception.py
- TP, FP displays the label of the object in the recognition result
- FN displays the label of the object to be output
TIER IV internal
```shell
webauto ci scenario run --project-id x2_dev --scenario-id 69b70360-de73-44dd-85af-f71317bae286 --scenario-version-id 5 --scenario-parameters 't4_dataset_id=7f45a005-1e2c-47a6-b14d-c93018710086,t4_dataset_version_id=0'
```
> feat: add object label list

- driving_log_replayer_cli/simulation/run.py
> fix: suppress error msg

- driving_log_replayer/launch/annotationless_perception.launch.py
record pointclound and objects
> feat(annotationless_perception): record pointclound and objects

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.15.3

- driving_log_replayer_cli/simulation/run.py
> chore: show exit status

- driving_log_replayer/launch/performance_diag.launch.py
> fix(performance_diag): disable perception

- driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> chore: show full uuid

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.15.4

- docs/quick_start/annotationless_perception.en.md
- docs/quick_start/annotationless_perception.ja.md
> docs: update annotationless_perception quick start run command

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.15.5

- driving_log_replayer/driving_log_replayer/evaluator.py
- driving_log_replayer/driving_log_replayer/obstacle_segmentation.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
> refactor: move function

- driving_log_replayer_cli/core/result.py
- driving_log_replayer_cli/simulation/__init__.py
- driving_log_replayer_cli/simulation/run.py
> chore: delete json conversion

- driving_log_replayer/scripts/traffic_light_evaluator_node.py
> chore: restore topic name

- driving_log_replayer/scripts/traffic_light_evaluator_node.py
Related to https://github.com/tier4/autoware_perception_evaluation/pull/73/commits/b354e8af6fb00641a9d9772c792fa6832983e23d
> chore: rename `FrameID.TRAFFIC_LIGHT` to `FrameID.CAM_TRAFFIC_LIGHT`

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.17.0

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.18.0

- docs/quick_start/.pages
- docs/quick_start/installation.en.md
- docs/quick_start/installation.ja.md
- docs/quick_start/perception.en.md
- docs/quick_start/perception.ja.md
- docs/quick_start/performance_diag.en.md
- docs/quick_start/performance_diag.ja.md
- sample/yabloc/scenario.yaml
> docs: update

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.18.1

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.0

- driving_log_replayer/package.xml
> feat: add rosbag2_storage_mcap

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.1

- driving_log_replayer/package.xml
> feat: add rosbag2_storage_mcap (#475)

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.2

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.3

- driving_log_replayer/driving_log_replayer/criteria/perception.py
- driving_log_replayer/driving_log_replayer/perception.py
- sample/perception/scenario.criteria.custom.yaml
- sample/perception/scenario.ja.yaml
- sample/perception/scenario.yaml
Add a criteria of yaw error named `YawError`.
I confirmed this feature works with the latest workflow.
This PR should be reviewed after https://github.com/tier4/driving_log_replayer/pull/425 has been merged.
> feat: add a criteria of yaw error

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.4

- docs/.pages
- docs/overview/command.en.md
- docs/overview/command.ja.md
- docs/trouble_shooting/index.en.md
- docs/trouble_shooting/index.ja.md
- add trouble shooting document
> docs: #221 trouble shooting

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.5

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
From the [PR#153](https://github.com/tier4/autoware_perception_evaluation/pull/153) in perception eval, `PercpetionAnalyzer**.analyze()` returns `PerceptionAnalysisResult`.
This PR apply it to DLR. 
Please review this PR with perception eval [PR#153](https://github.com/tier4/autoware_perception_evaluation/pull/153).
> feat: apply `PerceptionAnalysisResult`

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/driving_log_replayer/criteria/perception.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.18.4

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.7

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.18.5

- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_perception_2d.py
- driving_log_replayer/test/unittest/test_traffic_light.py
> fix: unit test

- driving_log_replayer/scripts/localization_evaluator_node.py
- Dealing with IndexError issues
> fix: check DiagnosticArray length

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/scripts/localization_evaluator_node.py
- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_perception_2d.py
- driving_log_replayer/test/unittest/test_traffic_light.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 1.18.6

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.8

- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
Update function interface in  `PerceptionEvaluationManager` by https://github.com/tier4/autoware_perception_evaluation/pull/179
```
colcon test --packages-select driving_log_replayer
colcon test-result
```
I have checked this PR in Evaluator
> feat: interface in add_frame_result

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_traffic_light.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.10

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.0.12

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.1.0

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.1.1

- log_evaluator/launch/log_evaluator.launch.py
- log_evaluator/log_evaluator/evaluator.py
- log_evaluator/scripts/annotationless_perception_evaluator_node.py
- log_evaluator/scripts/ar_tag_based_localizer_evaluator_node.py
- log_evaluator/scripts/eagleye_evaluator_node.py
- log_evaluator/scripts/localization_evaluator_node.py
- log_evaluator/scripts/obstacle_segmentation_evaluator_node.py
- log_evaluator/scripts/perception_2d_evaluator_node.py
- log_evaluator/scripts/perception_evaluator_node.py
- log_evaluator/scripts/performance_diag_evaluator_node.py
- log_evaluator/scripts/traffic_light_evaluator_node.py
- log_evaluator/scripts/yabloc_evaluator_node.py
- log_evaluator/test/unittest/test_evaluator.py
- replace dlr with log_evaluator
> chore: remove dlr

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.1.2

- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
- docs/use_case/localization.en.md
- docs/use_case/localization.ja.md
- docs/use_case/obstacle_segmentation.en.md
- docs/use_case/obstacle_segmentation.ja.md
- docs/use_case/perception.en.md
- docs/use_case/perception.ja.md
- docs/use_case/perception_2d.en.md
- docs/use_case/perception_2d.ja.md
- docs/use_case/performance_diag.en.md
- docs/use_case/performance_diag.ja.md
- docs/use_case/traffic_light.en.md
- docs/use_case/traffic_light.ja.md
> docs: update can topic name

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.1.3

- driving_log_replayer/package.xml
> fix: delete old msg

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/launch/annotationless_perception.launch.py
- driving_log_replayer/scripts/annotationless_perception_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.1.5

- ReleaseNotes.md
- docs/use_case/annotationless_perception.en.md
- docs/use_case/annotationless_perception.ja.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer/launch/annotationless_perception.launch.py
- driving_log_replayer/scripts/annotationless_perception_evaluator_node.py
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.2.0

- driving_log_replayer/scripts/ar_tag_based_localizer_evaluator_node.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/performance_diag_evaluator_node.py
- check DiagnosticArray msg length
> fix: check length

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.2.1

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.2.2

- docs/quick_start/localization.en.md
- docs/quick_start/localization.ja.md
Fix command option.
When we would like to specify the start time with `ros2 bag slice` command, we need to use `-b` option.
https://github.com/tier4/ros2bag_extensions?tab=readme-ov-file#ros2-bag-slice
> docs: fix command option

- .driving_log_replayer.cspell.json
- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.2.3

- docs/use_case/performance_diag.en.md
- docs/use_case/performance_diag.ja.md
- driving_log_replayer/driving_log_replayer/performance_diag.py
- driving_log_replayer/test/unittest/test_performance_diag.py
- sample/performance_diag/scenario.ja.yaml
- sample/performance_diag/scenario.yaml
> feat: diag apply pass rate

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.2.4

- .pre-commit-config.yaml
- driving_log_replayer/driving_log_replayer/obstacle_segmentation.py
- driving_log_replayer/test/unittest/test_lanelet2.py
- driving_log_replayer/test/unittest/test_obstacle_segmentation.py
- driving_log_replayer/test/unittest/test_perception.py
- driving_log_replayer/test/unittest/test_scenario.py
- driving_log_replayer_analyzer/driving_log_replayer_analyzer/data/__init__.py
- update linter and formatter tool version
> chore: update formatter linter

- .pre-commit-config.yaml
- .vscode/settings.json
- driving_log_replayer/driving_log_replayer/criteria/perception.py
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/scripts/perception_2d_evaluator_node.py
- driving_log_replayer/scripts/perception_evaluator_node.py
- driving_log_replayer/scripts/traffic_light_evaluator_node.py
- pyproject.toml
- replace formatter
- remove black
- use ruff format
> feat: remove black use ruff format

- .github/workflows/deploy-document.yaml
- .github/workflows/pre-commit.yaml
> feat: set python 3.10

- driving_log_replayer/package.xml
> fix: add exec_depend

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.0

- docs/use_case/.pages
> docs: index traffic_light and perception_2d

- docs/overview/index.en.md
- docs/overview/index.ja.md
> docs: update usage flow

- requirements.txt
It is no longer necessary to fix the pytest version.
https://github.com/ros2/launch/pull/777/files
if this actions is passed.
https://github.com/tier4/driving_log_replayer/actions/runs/10748310768
> chore: remove version fix of pytest

- requirements.txt
- update transforms3d version
closes: #556
> fix: fix transforms3d==0.4.2

- requirements.txt
- delete numpy version fix (No longer needed)
> chore: delete numpy version fix

- .driving_log_replayer.cspell.json
- requirements.txt
> fix: set numpy version

- ReleaseNotes.md
- dependency.repos
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.2

- .github/workflows/colcon-test.yaml
> ci: fix colcon test workflow

- .github/workflows/colcon-test.yaml
- .github/workflows/deploy-document.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/spell-check.yaml
- delete fetch-depth: 0
- use shallow clone
> fix: delete fetch-depth

- README.md
- docs/index.en.md
- docs/index.ja.md
> docs: add notice v2

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.4

- docs/overview/setup.en.md
- docs/overview/setup.ja.md
- driving_log_replayer/scripts/perception_evaluator_node.py
- [] New Features
These small changes fixes the setup docs and allows customisation of perception_evaluator.
> refactor: evaluator di

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.5

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.6

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.7

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.8

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.9

- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- fix condition to judge diag name
> fix: condition to judge diag name

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.3.11

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.4.0

- .github/workflows/colcon-test.yaml
- .github/workflows/deploy-document.yaml
- .github/workflows/lint-pull-request.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/spell-check.yaml
- .vscode/settings.json
- dependency.repos
- driving_log_replayer/driving_log_replayer/lanelet2_util.py
- driving_log_replayer/package.xml
- driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- driving_log_replayer/test/unittest/test_lanelet2.py
`lanelet2_extension` -> `autoware_lanelet2_extension`
- update dependency
- update package name
> fix: update lanelet2 extension

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.5.0

- ReleaseNotes.md
- driving_log_replayer/CHANGELOG.rst
- driving_log_replayer_analyzer/CHANGELOG.rst
- driving_log_replayer_msgs/CHANGELOG.rst
- pyproject.toml
> chore: release 2.7.0
