tier4/driving_log_replayer

driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
1. restore `Fail` status for frame result
2. delete meaningless frame result log
3. fix detection judgement logic 
https://github.com/tier4/driving_log_replayer/pull/37/files#diff-ff1376ca5c216f98f52bc448aac14bec473700dc2cebb15fc13d3db02793ad48R270
https://github.com/tier4/driving_log_replayer/pull/37/files#diff-ff1376ca5c216f98f52bc448aac14bec473700dc2cebb15fc13d3db02793ad48R179
If NonDetection is success, Info must be NumPoints is 0 and Distances are all 0.
So, if NonDetection is success, output empty list for `Info`
```json
"NonDetection": {
"Result": "Success",
"Info": [] // ←empty list
},
```
https://github.com/tier4/driving_log_replayer/pull/37/files#diff-ff1376ca5c216f98f52bc448aac14bec473700dc2cebb15fc13d3db02793ad48R188
```json
"Detection": {
"Result": "Fail",
"Info": [] // ←this …
```
=> fix: obstacle segmentation frame result

driving_log_replayer_cli/simulation/generate.py
There is a problem with the launch termination process not killing the process and causing it to become a zombie when tests are run continuously from CLI.
Added process to kill the process from the shell.
=> feat: cli kill zombie process

driving_log_replayer_cli/simulation/generate.py
If output directory include the string `ros`, the command terminates the bash itself.
Excluding /bin/bash and /bin/sh from the target so that the process does not die
```shell
❯ ps aux | grep -i ros
hyt         7603  0.0  0.0   2892   940 pts/0    S+   02:52   0:00 /bin/sh -c /bin/bash /home/hyt/out/rosdlr_out/2022-1207-025258/run.bash
hyt         7604  0.0  0.0  11932  4428 pts/0    S+   02:52   0:00 /bin/bash /home/hyt/out/rosdlr_out/2022-1207-025258/run.bash
```
=> fix: kill bash and sh command

driving_log_replayer_cli/simulation/generate.py
driving_log_replayer kills the process unrelated to ros2, that is including "ros" charactors in the line of `ps aux` outputs.
ex. /home/masahi**ros**akamoto/..
To extract only the child processes that name include "ros", "pgrep" is used.
- Check the code changes.
- Checkout this branch, reinstall driving_log_reolayer and run it to check if any degradation occurs when driving_log_reolayer closes.
- Adding above, after running the process that name includes "ros" (ex. run ros.sh),  run driving_log_replayer to check if the process keeps running when driving_log_reolayer closes.
- Any degradation occurred after applying this changes.
- "ros_check_if_alive.sh" process kept running after driving_log_reolayer closed.
[check_if_unrelated_process_alive.log](https://github.com/tier4/driving_log_repl …
=> fix: kill process unrelated to ros2

docs/use_case/perception_2d.en.md, docs/use_case/perception_2d.ja.md, driving_log_replayer/scripts/perception_2d_evaluator_node.py, driving_log_replayer/scripts/perception_evaluator_node.py, driving_log_replayer_cli/simulation/generate.py, sample/perception_2d/scenario.ja.yaml, sample/perception_2d/scenario.yaml
- support multiple cameras in perception_2d
- https://github.com/tier4/autoware_perception_evaluation/pull/64
output result likes below.
```shell
[perception_2d_evaluator_node.py-66]  Skipped Frames Count: 201
[perception_2d_evaluator_node.py-66] 
[perception_2d_evaluator_node.py-66] Ground Truth Num: 6962
[perception_2d_evaluator_node.py-66] 
[perception_2d_evaluator_node.py-66] mAP: 0.060 (Center Distance)
[perception_2d_evaluator_node.py-66] 
[perception_2d_evaluator_node.py-66] |      Label | car(100) |  bicycle(100) |  pedestrian(100) |  motorbike(100) | 
[perception_2d_evaluator_node.py-66] | :--------: | :---: | :---: | :---: | :---: |
[perception_2d_evaluator_node.py-66] | Predict_num | 1174 | 0 | 66 | 0 |
[perception_2d_evaluator_node.py-66] |         AP | 0.196 |  0.000 |  0.045 …
```
=> feat: #147 perception 2d support multi camera

sample/localization/scenario.ja.yaml, sample/localization/scenario.yaml
Automatic correction of z-coordinates is not working, so I set the z value appropriately.
https://github.com/autowarefoundation/autoware.universe/pull/2724
- fill z value
=> fix: fill z value of initial pose

driving_log_replayer/driving_log_replayer/yabloc.py, driving_log_replayer/scripts/yabloc_evaluator_node.py, driving_log_replayer/test/unittest/test_yabloc.py
- add unit test
To add test code for quality control of driving_log_replayer
The driving_log_replayer is a tool that operates as follows:
1. It subscribes to topics published by Autoware.
2. It determines success or failure based on the subscribed topic meeting certain conditions and writes the results to result.jsonl.
Therefore, add unit tests for the process of writing messages received from Autoware.
1. Prepare a message for success and a message for failure.
2. Test whether the Result class can correctly determine success and failure by passing messages to it.
Thanks to colcon test, unit tests are now automatically executed. Therefore, please verify the following:
1. Ensure that all checks in GitHub Actions have passed.
2. Verify that the contents of test_yabloc.py are correctly …
=> feat: yabloc test

driving_log_replayer/driving_log_replayer/criteria/perception.py
This PR removes `typing_extensions` because it can't be imported in WebAuto, like following log
```shell
[perception_evaluator_node.py-71] Traceback (most recent call last):
[perception_evaluator_node.py-71]   File "/home/autoware/autoware.proj/install/driving_log_replayer/lib/driving_log_replayer/perception_evaluator_node.py", line 44, in <module>
[perception_evaluator_node.py-71]     from driving_log_replayer.criteria import PerceptionCriteria
[perception_evaluator_node.py-71]   File "/home/autoware/autoware.proj/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/criteria/__init__.py", line 15, in <module>
[perception_evaluator_node.py-71]     from .perception import CriteriaLevel
[perception_evaluator_node.py-71]   File …
```
=> fix(perception): remove `typing_extensions`

driving_log_replayer/driving_log_replayer/launch_common.py, driving_log_replayer_cli/simulation/generate.py, pyproject.toml, sample/perception/scenario.fp.ja.yaml, sample/perception/scenario.fp.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml, sample/perception_2d/scenario.ja.yaml, sample/perception_2d/scenario.yaml
Update to enable specifying `perception_mode` in scenario file.
If not specified, default `perception_mode` specified in `autoware_launch` is used.
```yaml
ScenarioFormatVersion: 3.0.0
ScenarioName: sample_scenario
ScenarioDescription: sample scenario
SensorModel: sample_sensor_kit
VehicleModel: lexus
PerceptionMode: camera_lidar_fusion # ("camera_lidar_radar_fusion", "camera_lidar_fusion", "lidar_radar_fusion", "lidar","radar")
Evaluation:
...
```
=> feat(perception): allow to specify perception mode in scenario

docs/use_case/localization.en.md, docs/use_case/localization.ja.md, driving_log_replayer/driving_log_replayer/localization.py, driving_log_replayer/scripts/localization_evaluator_node.py
In the latest awf:autoware_universe, the output of relative Pose fixed by NDT has been added as an output topic for NDT.
https://github.com/autowarefoundation/autoware.universe/pull/5319
The topic name is `/localizaiton/pose_estimator/initial_to_result_relative_pose`.
Before the change, DiviringLogReplayer subscribed to the EKF Pose and compared the latest EKF Pose with the NDT Pose, causing some problems with time synchronization. 
(If the NDT takes about 100 msec to process, there will be a difference of about 100 msec between the timestamp that the sensor, which is the input to the NDT, has and the timestamp after the NDT processing.)
I would like to change this as the new indicator is more appropriate.
I plotted `Lateral Distance` and `Horizontal Distance` for the json obtained by …
=> perf: fixed to use `/localization/pose_estimator/initial_to_result_relative_pose`

ReleaseNotes.md, driving_log_replayer/CHANGELOG.rst, driving_log_replayer_analyzer/CHANGELOG.rst, driving_log_replayer_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 1.8.0

docs/scenario_format/index.en.md, docs/scenario_format/index.ja.md, driving_log_replayer_cli/simulation/__init__.py, driving_log_replayer_cli/simulation/generate.py, driving_log_replayer_cli/simulation/run.py, pyproject.toml, sample/perception/scenario.fp.ja.yaml, sample/perception/scenario.fp.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml, sample/perception_2d/scenario.ja.yaml, sample/perception_2d/scenario.yaml
- downgrade scenario format (3.1.0 -> 3.0.0)
- revert https://github.com/tier4/driving_log_replayer/pull/279
- add perception mode to simulation run argument
- You can specify the perception_mode with the -m or --perception-mode option.
- However, perception_2d is currently fixed with `camera_lidar_fusion`, no matter what is passed to perception_mode.
- https://github.com/tier4/driving_log_replayer/blob/develop/driving_log_replayer/launch/perception_2d.launch.py#L33
```shell
❯ driving_log_replayer simulation run -p perception -m camera_lidar_fusion --rate 0.5
$HOME/out/perception/2023-1108-144009
<< generating launch command >>
launch command generated! => ros2 launch driving_log_replayer perception.launch.py perception_mode:=camera_lidar_fusion …
```
=> feat: parameterize perception mode

driving_log_replayer/driving_log_replayer/criteria/perception.py
As discussed in https://github.com/tier4/driving_log_replayer/issues/304, when both ground truth and perception results do not exist it should be considerd as `success`.
Try with sample project.
=> fix no data criteria

driving_log_replayer/driving_log_replayer/launch_common.py, driving_log_replayer/launch/ar_tag_based_localizer.launch.py, driving_log_replayer/launch/eagleye.launch.py, driving_log_replayer/launch/localization.launch.py, driving_log_replayer/launch/obstacle_segmentation.launch.py, driving_log_replayer/launch/perception.launch.py, driving_log_replayer/launch/perception_2d.launch.py, driving_log_replayer/launch/performance_diag.launch.py, driving_log_replayer/launch/traffic_light.launch.py, driving_log_replayer/launch/yabloc.launch.py, driving_log_replayer_cli/simulation/__init__.py, driving_log_replayer_cli/simulation/generate.py, driving_log_replayer_cli/simulation/run.py
- override record topic using launch argument
- use `override_record_topics:=true override_topics_regex:=\^/clock\$\|\^/tf\$\|/sensing/lidar/concatenated/pointcloud`
- notice: escape ^ $ | 
```shell
ros2 launch driving_log_replayer perception.launch.py perception_mode:=lidar scenario_path:=/home/hyt/data/perception/sample/scenario.yaml result_json_path:=/home/hyt/out/perception/2023-1114-162832/sample/sample_dataset/result.json play_rate:=0.5 play_delay:=10.0 input_bag:=/home/hyt/data/perception/sample/t4_dataset/sample_dataset/input_bag result_bag_path:=/home/hyt/out/perception/2023-1114-162832/sample/sample_dataset/result_bag map_path:=/home/hyt/map/oss vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit vehicle_id:=default override_record_topics:=True …
```
=> feat: override record topics

driving_log_replayer/driving_log_replayer/perception.py, driving_log_replayer/driving_log_replayer/perception_2d.py, driving_log_replayer/driving_log_replayer/traffic_light.py
- fix validation error when custom criteria level used
I created scenario using custom criteria level and confirmed this scenario works fine
```yaml
ScenarioFormatVersion: 3.0.0
ScenarioName: perception_use_bag_concat_data
ScenarioDescription: sensing_module_off_and_use_pointcloud_in_the_rosbag
SensorModel: sample_sensor_kit
VehicleModel: sample_vehicle
Evaluation:
UseCaseName: perception
UseCaseFormatVersion: 0.6.0
Datasets:
- sample_dataset:
VehicleId: default # Specify VehicleId for each data set.
LaunchSensing: false # Specifies whether the sensing module should be activated for each dataset. if false, use concatenated/pointcloud in bag
LocalMapPath: $HOME/map/oss # Specify LocalMapPath for each data set.
Conditions:
PassRate: 99.0 # How much (%) of the evaluation attempts are …
```
=> fix: perception criteria validation bug

.github/workflows/colcon-test.yaml
- remove deprecating command
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: set-output command

driving_log_replayer_cli/simulation/generate.py, driving_log_replayer_cli/simulation/run.py
- Save the log displayed in the console as a file in the output directory
1. checkout `feat/cli-output-console-log` 
2. install cli `pipx install . -f`
3. run simulation `dlr simulation run`
4. `console.log` is saved in your output directory
like blow image
=> feat: cli output console log

driving_log_replayer/driving_log_replayer/launch_common.py, driving_log_replayer/launch/ar_tag_based_localizer.launch.py, driving_log_replayer/launch/localization.launch.py, driving_log_replayer/launch/yabloc.launch.py
The implicitly passed arguments `pose_source` and `twist_source` are overwritten in the `get_autoware_launch` function's given default values.
Currently, there is no problem because the default value specified in `get_autoware_launch` matches the default value written in launch.
However, if the default value in launch is changed, unintentional overwriting will occur.
To prevent unintentional overwriting, do not specify `pose_source` and `twist_source` as arguments to autoware.launch unless explicitly specified.
- https://github.com/autowarefoundation/autoware.universe/issues/2695
=> fix: overwrite pose_source and twist_source

driving_log_replayer/driving_log_replayer/criteria/perception.py, driving_log_replayer/driving_log_replayer/perception.py, driving_log_replayer/driving_log_replayer/perception_2d.py, driving_log_replayer/driving_log_replayer/traffic_light.py, driving_log_replayer/test/unittest/test_perception.py, sample/perception/scenario.criteria.custom.yaml, sample/perception/scenario.fp.ja.yaml, sample/perception/scenario.fp.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml
In order to support yaw-based error evaluation for `Perception` scenarios, **I would like to add `metrics_score_maph` criteria in driving_log_replayer**, which is based on Maph. Note that `metrics_score` ideally should be renamed to `metrics_score_map`, but I do not make this change to maintain backward compatibility. 
In addition, in order to enable users to evaluate a scenario using two or more metrics (e.g. `metrics_score` and `metrics_score_maph`), I propose to change the scenario format so that `CriteriaMethod` can also take List[CriteriaMethod].
Ran with following scenario yaml files and confirmed that `dlr simulation run -p perception ...` runs successfully.
```yaml
Conditions:
PassRate: 95.0
CriteriaMethod: metrics_score
CriteriaLevel: 10.0
```
```yaml
Conditions:
PassRate: 95.0 …
```
=> feat: add maph criteria

driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
- Fix access to null object
- Fixed a runtime error when Conditions.NonDetection is null.
```shell
[obstacle_segmentation_evaluator_node.py-66]   File "/home/autoware/pilot-auto.x1/install/driving_log_replayer/lib/driving_log_replayer/obstacle_segmentation_evaluator_node.py", line 358, in <module>
[obstacle_segmentation_evaluator_node.py-66]     main()
[obstacle_segmentation_evaluator_node.py-66]   File "/home/autoware/pilot-auto.x1/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/evaluator.py", line 449, in wrapper
[obstacle_segmentation_evaluator_node.py-66]     evaluator = func()
[obstacle_segmentation_evaluator_node.py-66]   File "/home/autoware/pilot-auto.x1/install/driving_log_replayer/lib/driving_log_replayer/obstacle_segmentation_evaluator_node.p …
```
=> fix: add handling of cases where non_detection is disabled

driving_log_replayer/driving_log_replayer/criteria/perception.py, driving_log_replayer/driving_log_replayer/perception.py
Add support of `label` metrics.
This metrics calculating score with the following policy:
- Check whether label is correct if the object result has the pair of GT.
- If the result is FN, it means there is no corresponding GT, skip scoring.
scenario example:
```
Conditions:
Criterion:
- PassRate: 95.0 # How much (%) of the evaluation attempts are considered successful.
CriteriaMethod: label # Method name of criteria (num_tp/label/metrics_score)
CriteriaLevel: hard # Level of criteria (perfect/hard/normal/easy, or custom value 0.0-100.0)
Filter:
Distance: 0.0-50.0 # [m] null [Do not filter by distance] or lower_limit-(upper_limit) [Upper limit can be omitted. If omitted value is 1.7976931348623157e+308]
...
```
=> feat: add support of label metrics

driving_log_replayer/driving_log_replayer/localization.py, driving_log_replayer/test/unittest/test_localization.py
- fix default value of EvaluationItem.success
TIER IV internal
Applying this PR changes the result from Success to Fail
```shell
wasim run --project-id x2_dev --scenario-id 2d6d0b4b-ed50-4657-98f4-6e48b14eddaf --scenario-version 10
```
same as 06fab5312529ec06573ff7aa41eea2b88119369b
=> fix: localization default success value

docs/quick_start/annotationless_perception.en.md, docs/quick_start/annotationless_perception.ja.md, docs/use_case/annotationless_perception.en.md, docs/use_case/annotationless_perception.ja.md, driving_log_replayer/driving_log_replayer/launch_common.py, driving_log_replayer/launch/annotationless_perception.launch.py, driving_log_replayer/test/unittest/test_annotationless_perception.py, sample/annotationless_perception/scenario.ja.yaml, sample/annotationless_perception/scenario.yaml
- set use_perception_online_evaluator=true in `annotationless_perception.launch.py`
Please confirm that you can evaluate annotationless_perception without `-l  use_perception_online_evaluator=true` option
```shell
dlr simulation run -p annotationless_perception
```
=> feat: set use_perception_online_evaluator=true by default

driving_log_replayer/driving_log_replayer/launch_common.py
closes: #57
- add use-sim-time option to record command
The use-sim-time option of ros2 record was changed to start the record after clock comes. See help for the following command
Previously, if the topic was displayed before the clock came, the time would be 0 seconds, i.e., 1970-01-01T00:00:00, and ros time would jump at the moment the clock came.
Therefore, it was necessary to adjust the record start timing, but now the record side adjusts the record start timing.
It is now equivalent to ros1.
```shell
❯ ros2 bag record -h
usage: ros2 bag record [-h] [-a] [-e REGEX] [-x EXCLUDE] [--include-unpublished-topics] [--include-hidden-topics] [-o OUTPUT] [-s {my_test_plugin,sqlite3,mcap}] [-f {s,a}] [--no-discovery]
...
--use-sim-time        Use simulation time for message timestamps by …
```
=> feat: use sim time

driving_log_replayer/driving_log_replayer/criteria/perception.py, driving_log_replayer/driving_log_replayer/perception.py, sample/perception/scenario.criteria.custom.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml
Add support of velocity criteria.
- `VELOCITY_X_ERROR`: Calculate an error of x direction velocity.
- `VELOCITY_Y_ERROR`: Calculate an error of y direction velocity.
- `SPEED_ERROR`: Calculate an error of velocity norm.
Each criteria calculates the absolute error in scalar.
=> feat(perception): add support of velocity criteria

driving_log_replayer/driving_log_replayer/criteria/perception.py
Update to return 100.0 in `NumTP` if there is no objects.
=> fix: if there is no objects returns 100.0

driving_log_replayer/scripts/perception_evaluator_node.py
Fix error that `conf_mat_dict` is referenced before assignment
=> fix: avoid error that `conf_mat_dict` is referenced before assignment

driving_log_replayer/driving_log_replayer/criteria/perception.py, driving_log_replayer/driving_log_replayer/perception.py, driving_log_replayer/driving_log_replayer/perception_2d.py, driving_log_replayer/driving_log_replayer/traffic_light.py
Related to [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C02G6HT8TNX/p1719459096370449?thread_ts=1718065046.566139&cid=C02G6HT8TNX).
Add a new criteria named `NumGtTP` only considering whether all ground truths are TP even if there are any FP objects.
In scenarios, please specify as follows:
```yaml
Criterion:
- PassRate: ...
CriteriaMethod: num_gt_tp
CriteriaLevel: ...
Filter:
Distance: ...
```
=> feat: add support of GT TP criteria

driving_log_replayer/driving_log_replayer/criteria/perception.py
This PR fixes invalid attribute access to `PassFailResult.critical_ground_truth_objects` updated in https://github.com/tier4/autoware_perception_evaluation/pull/179.
Run scenario with criteria: `num_gt_tp`.
=> fix: resolve invalid access to `critical_ground_truth_objects`

driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
Related to https://github.com/tier4/driving_log_replayer/pull/452.
Fix following error while converting evaluation results:
```shell
[perception_evaluator_node.py-68]   File "/home/autoware/pilot-auto/install/driving_log_replayer/lib/driving_log_replayer/perception_evaluator_node.py", line 265, in perception_cb
[perception_evaluator_node.py-68]     marker_ground_truth, marker_results = self._result.set_frame(
[perception_evaluator_node.py-68]   File "/home/autoware/pilot-auto/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/perception.py", line 172, in set_frame
[perception_evaluator_node.py-68]     self._frame[criterion.name] = criterion.set_frame(frame)
[perception_evaluator_node.py-68]   File …
```
=> fix(perception): resolve invalid access to `None`

driving_log_replayer/scripts/traffic_light_evaluator_node.py
Change types from `autoware_perception_msgs.msg._traffic_light_element.TrafficLightElement` to `float` to analyze `auto-evalator`.
Related links: https://github.com/tier4/auto-evaluator/pull/206
None. But I checked this on [`Evaluator`](https://evaluation.ci.tier4.jp/evaluation/reports/ca2e697d-2a54-5c19-841b-3ba89fca7aef?project_id=prd_jt) and local `auto-evalator`
=> fix(traffic_light): remove autoware_perception_msgs in traffic_light

docs/use_case/annotationless_perception.en.md, docs/use_case/annotationless_perception.ja.md, driving_log_replayer/launch/annotationless_perception.launch.py, driving_log_replayer/scripts/annotationless_perception_evaluator_node.py
https://github.com/autowarefoundation/autoware.universe/pull/8152
https://star4.slack.com/archives/C03QW0GU6P7/p1721700599221729
/dignostic/*と/diagnostics/*かつ、今後diag(閾値と比較)とmetrics(値のみの計算)を分離する話があるため、トピックのリネームをしています。
plannig, controlにも同様な変更が必要です :bow:
=> feat(annotationless_perception): rename input diag topics

driving_log_replayer/scripts/obstacle_segmentation_evaluator_node.py
Without diag msgs, msg.status[0] causes the following error
Fixed to work around this.
```
[obstacle_segmentation_evaluator_node.py-75]   File "/home/autoware/pilot-auto.x1/install/driving_log_replayer/lib/driving_log_replayer/obstacle_segmentation_evaluator_node.py", line 306, in diag_cb
[obstacle_segmentation_evaluator_node.py-75]     diag_status: DiagnosticStatus = msg.status[0]
[obstacle_segmentation_evaluator_node.py-75] IndexError: list index out of range
[component_container_mt-1] [INFO] [1721737631.943992032] [perception.obstacle_segmen
```
Autoware Evaluator
before [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/04bca0a6-2376-5dfd-a509-3da2b9821227?project_id=X8ft5pPN)
after [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/fed5c090-70a5 …
=> fix: fix diag index error

driving_log_replayer/driving_log_replayer/evaluator.py, driving_log_replayer/package.xml, driving_log_replayer/scripts/debug/calc_transform_node.py, driving_log_replayer/test/unittest/test_evaluator.py, driving_log_replayer/test/unittest/test_obstacle_segmentation.py
This PR updates to use `pyquaterion` instead of `tf_trasnformations` in order to avoid the following error:
```shell
[perception_evaluator_node.py-66] Traceback (most recent call last):
[perception_evaluator_node.py-66]   File "/home/autoware/pilot-auto/install/driving_log_replayer/lib/driving_log_replayer/perception_evaluator_node.py", line 42, in <module>
[perception_evaluator_node.py-66]     from driving_log_replayer.evaluator import DLREvaluator
[perception_evaluator_node.py-66]   File "/home/autoware/pilot-auto/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/evaluator.py", line 45, in <module>
[perception_evaluator_node.py-66]     from tf_transformations import euler_from_quaternion
[perception_evaluator_node.py-66]   File …
```
=> fix: use `pyquaterion` instead of `tf_transformations`

.github/workflows/colcon-test.yaml, .github/workflows/deploy-document.yaml, .github/workflows/pre-commit.yaml, .github/workflows/spell-check.yaml
avoid below
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
- update github actions
=> chore: update github actions to avoid Node 16

driving_log_replayer/driving_log_replayer/launch_common.py
This PR will add `autoware_` prefix for `map_height_fitter` in `launch_common.py`' `get_map_height_fitter`.
This is for https://github.com/autowarefoundation/autoware.universe/pull/8421
=> fix(driving_log_replayer): add autoware prefix for map_height_fitter package

ReleaseNotes.md, driving_log_replayer/CHANGELOG.rst, driving_log_replayer_analyzer/CHANGELOG.rst, driving_log_replayer_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 2.3.1

driving_log_replayer/driving_log_replayer/perception_eval_conversions.py, driving_log_replayer/scripts/perception_evaluator_node.py
Author wants to add covariance information into jsonl. This will help to evaluate centerpoint_sigma model. See https://tier4.atlassian.net/browse/RT1-8002 for TIER IV members.
This PR must merged after https://github.com/tier4/autoware_perception_evaluation/pull/190.
Run evaluator and see the result.
=> feat: add covariance information in jsonl

driving_log_replayer_cli/core/config.py, driving_log_replayer_cli/simulation/run.py
1. When a scenario file is missing, the code now prints a red error message and continues to the next dataset.
2. When parsing the Datasets from the t4_dataset path, if there is an exception, the code now prints a red error message with the exception details.
=> fix: Handle missing scenario file and invalid Datasets

driving_log_replayer/launch/localization.launch.py
I have added topics that are useful for analysis.
I have confirmed that driving_log_replayer works well and the topics are recorded normally.
Note : `/localization/reference_kinematic_state` is a optional topic, which is not in sample rosbag.
Please check that it is working properly.
=> fix: add record topics in localization scenario

ReleaseNotes.md, driving_log_replayer/CHANGELOG.rst, driving_log_replayer_analyzer/CHANGELOG.rst, driving_log_replayer_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 2.3.10

driving_log_replayer/driving_log_replayer/launch_common.py, driving_log_replayer/package.xml
renames component_state_monitor -> autoware_component_state_monitor
This should be reviewed with https://github.com/autowarefoundation/autoware.universe/pull/9961
=> feat: add autoware_ prefix to component_state_monitor

driving_log_replayer/test/unittest/test_scenario.py
- add unit test to confirm int value properly convert to float
- related PR
- <https://github.com/tier4/driving_log_replayer_v2/pull/82>
If CI for github actions is passed, it is OK.
This PR only updates the unit test code.
=> chore: Confirmation that the pydantic model will properly convert to float
